apiVersion: 1

datasources:
  - name: InfluxDB-k6
    uid: fuc-influxdb-k6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    isDefault: true
    jsonData:
      httpMode: GET
